import Calendar from "./calendar/";
import Dashboard from "./dashboard/";
import Login from "./Login";
import Logout from "./Logout";
import Register from "./Register";
import Users from "./Users";
import Preferences from "./Preferences";
import StudentRoster from "./StudentRoster";
const menu = ["Login", "Calendar", "Dashboard", "Roster", "Preferences", "Register"];
const adminMenu = ["Login", "Calendar", "Dashboard", "Users", "Roster", "Preferences"];
export { Calendar, Dashboard, Login, Users, StudentRoster, Logout, Preferences, Register,menu, adminMenu };
